### ISSUE TITLE
Pré-remplir le formulaire 

### ISSUE THREAD

**Issue by bluke** [ensiie/ragots#13]
Je suggère de pré-remplir le formulaire avec "Il parait que" plutôt que de laisser la situation actuelle ou la phrase disparaît lorsque l'on commence a taper. Les ragots devrait commencer comme ça de toute façon.

**Comment by Soulou** [comment]
Pourquoi forcément "il parait que", ça pourrait être "Il semblerait que", ou "On aurait vu" ou encore "La rumeur court que". Bref je suis contre !

**Comment by barodeur** [comment]
Meme si parfois certaines personnes vont écrire "Il semblerait que"… Je suis d'accord avec @bluke pour dire que proposer un pattern par défaut (le plus utilisé) n'est pas une mauvaise idée.

**Comment by wikii** [comment]
Moi je suis pas trop pour non plus, les ragots commencent de pleins de manières différentes au final.

**Comment by bluke** [comment]
Je suis d'accord avec @barodeur .
De plus j'ai peur que avec la solution actuelle les gens vois "Il parait que", ce mettent a écrire la suite et qu'on ait des  ragot auquel il manque un début.

**Comment by barodeur** [comment]
En fait c'est pas forcément le fait de commencer par "Il parait que" qui est important, c'est plutôt d'encourager à utiliser le conditionnel.
Utiliser un pattern par défaut me semble un bon moyen d'encourager au conditionnel. Les utilisateurs restent libres de le changer s'il le veulent.

**Comment by bluke** [comment]
En fait il s’avère que cette modification ne fait pas bon ménage avec l'autofocus.

**Comment by barodeur** [comment]
On en est où avec cette issue ?

**Comment by bluke** [comment]
Le focus et le préremplissage ne font pas bon ménage. On c'e retrouve avec
le curseur avant "il parait que". ce qui est a mon avis moins bien que la
situation actuelle.

2013/3/27 Paul Chobert notifications@github.com

**Comment by barodeur** [comment]
Je ferme du coup.
